//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int id_user { get; set; }
        public string nom_user { get; set; }
        public string prenom_user { get; set; }
        public string mail_user { get; set; }
        public string motdepasse_user { get; set; }
    }
}
